import time

print("Hey, hey, hey")
time.sleep(2)
print("I got a condo in Manhattan")
time.sleep(2)
print("Baby girl, what's hatnin'?")
time.sleep(2)
print("You and your ass invited")
time.sleep(2)
print("So gon' and get to clappin'")
time.sleep(2)
print("Go pop it for a player, pop-pop it for me")
time.sleep(2)
print("Turn around and drop it for a player, drop-drop it for me")
time.sleep(2)
print("I'll rent a beach house in Miami")
time.sleep(2)
print("Wake up with no jammies")
time.sleep(1)
print("(Nope)")
time.sleep(1)
print("Lobster tail for dinner")
time.sleep(2)
print("Julio, serve that scampi")
time.sleep(2)
print("You got it if you want it, got, got it if you want it")
time.sleep(2)
print("Said you got it if you want it, take my wallet if you want it, now")
time.sleep(2)
print("TOMMYINNITS PART")
time.sleep(3)
print("Jump in the Cadillac\n(Girl, let's put some miles on it)\nAnything you want\n(Just to put a smile on you)\nYou deserve it baby, you deserve it all\nAnd I'm gonna give it to you\nGold jewelry shining so bright\nStrawberry champagne on ice\nLucky for you, that's what I like, that's what I like\nLucky for you, that's what I like, that's what I like")
time.sleep(30)
print("Exiting...")
time.sleep(1)